behaviors:
  Grid_Tile_Agent:
    trainer_type: sac

    hyperparameters:
      batch_size: 32
      buffer_size: 10000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      buffer_init_steps: 100
      tau: 0.005
      steps_per_update: 1.0
      init_entcoef: 0.2

    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 1

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 1000
    time_horizon: 32
    summary_freq: 100